name: CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["8.0.0"]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure the Bazel version
        run: |
          echo "${{ matrix.version }}" > .bazelversion

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelrc: |
            common --enable_bzlmod
            build --color=yes
            build --show_timestamps

      - name: Run Bazel test under the tests directory
        run: bazel test //...